language: cpp

os:
  - osx

compiler:
  - clang

osx_image: xcode9.2

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JKQr/D593Z3oMuBn4GOw/Y5cBTkDdSWS8+VgJoWRf/v2/KWAejWzYS/lqEZ07BbS3aoK881d6Zlt23jARdERWnOgYxT2Xbocx1dUoR1W6VCB5KFkqlN2/Y9BUh+mIwcZGqHQl/U4F14UFzMFlRJQKmv9NMKBhRl4JcVv8kT3p3MjmlpBfgJm2wxuJGc2zE4fgiuoDDQ84jPDxIAz3YiKOORhSne4KNLxN4fA/l9jwo0Smtgn1hhr7PdShkv1iCmjp1vMsRKtlQpnZTmL5jD/Mn0Pc28ZNs1QgzjVpptIMGBNfm0+K0DnPQgXV2XuQ0N9miNj0n7ZHCQ5BI+wLhaQHNaTNlXOA95s6P+7rmgefAjUMNdInMUx7mxNfoFghf7NzNBNpAf2QKnvEIkNbhQAEGVOZz0VSo2lAlc17UPAeXTwzyM8/xVBmRZPM6XsR/zf/7xmpNI0ljRiaLcD/GCDZ8yv5C5+k5LiUbbx1zK4IuElcvOJYsmB4/S3d8/wSYQ4ZhJotgRJUqXbKZTToZXcUBmfqj8qRFdAAvePmxPq3HuieqdzkaBev7r12obamZqoM2Mpnb5GNDB0dD5eSvYfSBIRBYeb+su3fvkmBPTq0UJ/NeYRUd1BwLrmEOhGJqPrg3EotDhwOdUnzyvx67XQoy4HyW4dSv3WqO/Mfi1SaOQ=
  file: Test
  on:
    repo: vinyldarkscratch/travis-release-testing
    tags: true
